# Multiply from line 13 to 19 if you want multiple sync branches

name: Sync gh-pages branch

on:
  push:
    branches: ['dev']

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev branch into gh-pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: gh-pages
          github_token: '${{ secrets.GITHUB_TOKEN }}'

  build-gh-pages-app:
    needs: [sync-branch]
    runs-on: ubuntu-latest
    steps:
      - name: Go to gh-pages
        working-directory: ${{github.workspace}}
        run: |
          git switch gh-pages
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install client's dependencies
        run: yarn install
      - name: Build client app and move to docs folder
        run: yarn gh-pages:linux
