# Multiply from line 13 to 19 if you want multiple sync branches

name: Sync gh-pages branch
on:
  push:
    branches: ['dev']
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev branch into gh-pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: gh-pages
          github_token: ${{ github.token }}
